name: Essentials
version: '${project.version}'
main: io.github.sidneiimatos.essentials.Essentials
commands:
  fly:
  site:
  youtube:
    aliases: [yt, miniyt, parceiros]
  feed:
    aliases: [heal, food]